apiVersion: v1
kind: Secret
metadata:
  name: cloud-sql-secret
  namespace: my-space
type: Opaque
data:
  # The Secret resource contains two maps: data and stringData.
  # The data field is used to store arbitrary data, encoded using base64.
  # The stringData field is provided for convenience, and it allows you to provide the same data as unencoded strings.
  # You can use the command 'echo -n <your-string> | base64' to encode your strings to base64 format.
  username: cHJhdA==
  password: Qm9udUAyMTIz
  database: VEVTVF9EQg==
